# Generated by Django 5.0.1 on 2024-06-06 15:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('nomer_id', models.IntegerField(blank=True, null=True, verbose_name='Номер сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('wiki_cat_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категории базы знаний',
                'verbose_name_plural': 'Категории базы знаний',
                'ordering': ['nomer_id'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('opisanie_full', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Описание задачи полное')),
                ('opisanie_mini', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Описание краткое')),
                ('wiki_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('language', models.CharField(blank=True, choices=[('bsh', 'BASH'), ('c', 'C'), ('cc', 'CC'), ('cpp', 'cpp'), ('cs', 'CS'), ('csh', 'Shell'), ('cyc', 'CYC'), ('cv', 'CV'), ('htm', 'HTM'), ('html', 'HTML'), ('java', 'JAVA'), ('js', 'JAVASCRIPT'), ('m', 'M'), ('mxml', 'MXML'), ('perl', 'PERL'), ('pl', 'PL'), ('pm', 'PM'), ('py', 'PYTHON'), ('rb', 'Rubby'), ('sh', 'Shell'), ('xhtml', 'XHTML'), ('xml', 'XML'), ('xsl', 'XSL')], default='', max_length=255, null=True, verbose_name='выбрать язык подцветки кода')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template_name', models.CharField(blank=True, max_length=70, verbose_name='Выбор шаблона')),
                ('kurs_cat', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.wiki_cat', verbose_name='задача относится к категории')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задача',
                'ordering': ['-created_at'],
            },
        ),
    ]
