# Generated by Django 5.0.1 on 2024-06-06 15:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family_tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('otchestvo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('familiya', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='family_tree', verbose_name='Фотография')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('drevo_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('opisanie_full', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Описание')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, null=True, verbose_name='Пол')),
                ('date1', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date2', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drevo.family_tree')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='drevo.family_tree', verbose_name='Партнеры')),
                ('parents_f', models.ManyToManyField(blank=True, related_name='father', to='drevo.family_tree', verbose_name='Отец')),
                ('parents_m', models.ManyToManyField(blank=True, related_name='mother', to='drevo.family_tree', verbose_name='Мать')),
            ],
            options={
                'verbose_name': 'Генеалогическое Дерево',
                'verbose_name_plural': 'Генеалогическое Дерево',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Family_tree_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='family_tree_files', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_tree_files', to='drevo.family_tree', verbose_name='Выбранные файлы')),
            ],
            options={
                'verbose_name': 'Документы, файлы',
                'verbose_name_plural': 'Документы, файлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Family_tree_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='family_tree_images2', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_tree_images', to='drevo.family_tree', verbose_name='Выбранные фотографии')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-created_at'],
            },
        ),
    ]
