# Generated by Django 5.0.1 on 2024-06-06 15:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(max_length=255, verbose_name='Название')),
                ('opisanie', django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Описание')),
                ('date1', models.CharField(max_length=255, verbose_name='Дата в кружке')),
                ('date2', models.DateField(blank=True, default='', null=True, verbose_name='Дата')),
                ('img_tovar', models.ImageField(blank=True, max_length=255, null=True, upload_to='img_tovar', verbose_name='Картинка')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео(https://youtu.be/)')),
                ('video2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео(/media/video/)')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template_name', models.CharField(blank=True, max_length=70, verbose_name='Выбор шаблона')),
            ],
            options={
                'verbose_name': 'Путешествия',
                'verbose_name_plural': 'Путешествия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео(https://youtu.be/)')),
                ('video2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео(/media/video/)')),
                ('travel_video_quality', models.CharField(choices=[('option1', 'Full HD'), ('option2', 'HD'), ('option3', 'SD')], default='option1', max_length=20, verbose_name='Качество обложки')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travelvideo', to='travel.travelcart', verbose_name='Выбранное путешествие')),
            ],
            options={
                'verbose_name': 'Видео из путешествия',
                'verbose_name_plural': 'Видео из путешествия',
                'ordering': ['-created_at'],
            },
        ),
    ]
